
app_identifier("de.rki.coronawarnapp-dev")

username("cwa.technical-user@sap.com")

automatic_release(true)

overwrite_screenshots(true)

skip_screenshots(true)

skip_metadata(true)

app_icon("./ENA/ENA/Resources/Assets/AppIcon.xcassets")

team_id("523TP53AQF")
