# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# A list of supported languages

ENV["LC_ALL"] = "de_DE"
ENV["LANG"] = "de_DE"

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
    xcversion(version: "11.6")
  end

  desc "Update license file"
  lane :update_licenses do
    update_third_party_notice()
  end

  desc "Build project"
  lane :build do
    build_ios_app(
      skip_codesigning: true,
      export_method: "ad-hoc",
      skip_package_ipa: true,
      destination: "platform=iOS Simulator,OS=13.6,name=iPhone 11",
      scheme: "ENA"
    )
  end

  desc "Build project (Community)"
  lane :build_community do
    build_ios_app(
      skip_codesigning: true,
      export_method: "ad-hoc",
      skip_package_ipa: true,
      destination: "platform=iOS Simulator,OS=13.6,name=iPhone 11",
      scheme: "ENACommunity"
    )
  end

  desc "Run tests"
  lane :test do
    # UI Tests
    run_tests(
      scheme: "ENAUITests",
      devices: ["iPhone 11"]
    )

    # Unit Tests
    run_tests(
      scheme: "ENATests",
      devices: ["iPhone 11"]
    )

    swiftlint(
      mode: :lint,
      output_file: "swiftlint.result.json",
      config_file: "ENA/.swiftlint.yml",
      raise_if_swiftlint_error: true,
      reporter: "sonarqube"
    )

    # Gather code coverage
    xcov(
      workspace: "ENA.xcworkspace",
      scheme: "ENATests",
      markdown_report: true,
      html_report: false,
      output_directory: "fastlane/test_output"
    )
  end

  desc "Build and upload for testing"
  lane :betaRelease do
    match(
      type: "appstore"
    )

    build_ios_app(
      scheme: "ENA",
      configuration: "TestFlight",
      clean: true
    )

    upload_to_testflight(
      username: "cwa.technical-user@sap.com",
      apple_id: "1515713549",
      skip_waiting_for_build_processing: true,
      skip_submission: true,  # only upload
    )
  end

  desc "Ad hoc distribution"
  lane :adHocDistribution do
    match(
      type: "adhoc"
    )

    build_ios_app(
      scheme: "ENA",
      configuration: "AdHoc",
      export_method: "ad-hoc",
      clean: true
    )

    appcenter_upload(
      api_token: ENV["MS_APP_CENTER_TOKEN"],
      owner_name: "Corona-Warn-App",
      owner_type: "organization",
      app_name: "Corona-Warn-App",
      file: "ENA.ipa"
    )
  end

  desc "Update GitHub Pages"
  lane :updateDocs do

    # Create docs
    jazzy(
     config: ".jazzy.yaml"
    )

    # Deploy to gh pages
    sh("npm install -g --silent gh-pages@2.0.1")
    sh("gh-pages --dist ../../../docs/swift-doc")

  end

end
