# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Build project"
  lane :build do
    build_ios_app(
      skip_codesigning: true,
      skip_archive: true,
      destination: "platform=iOS Simulator,OS=13.5,name=iPhone 11",
      scheme: "ENA"
    )
  end

  desc "Run tests"
  lane :test do
    # Unit Tests
    run_tests(
      scheme: "ENATests",
      devices: ["iPhone 11"]
    )

    # UI Tests
    run_tests(
      scheme: "ENAUITests"
      # tbc..
    )
  end
end
