# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 8",
    "iPhone 11 Pro"
])

ios_version(
  "14.4"
)

# Languages are set individually in CI
# languages([
#   "en-US",
#   "de-DE",
#   "bg-BG",
#   "ro-RO",
#   "pl-PL",
#   "tr-Tr"
# ])

# The name of the scheme which contains the UI Tests
scheme("ENAScreenshots")
testplan("Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# We keep existing screenshots. In the CI there should be none present
clear_previous_screenshots(false)

# Because the simulator is a wonderful but unstable tool
stop_after_first_error(true)
number_of_retries(2)

headless(false)
erase_simulator(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
# override_status_bar(true)

localize_simulator(true)

disable_slide_to_type(true)

skip_helper_version_check(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
