////
// 🦠 Corona-Warn-App
//

import Foundation

enum DCCValidationError: Error {
	
	// MARK: - Internal
	
	case TECHNICAL_VALIDATION_FAILED (DCCValidationReport)
	case ACCEPTANCE_RULE_CLIENT_ERROR (DCCValidationReport)
	case ACCEPTANCE_RULE_JSON_ARCHIVE_FILE_MISSING (DCCValidationReport)
	case ACCEPTANCE_RULE_JSON_ARCHIVE_SIGNATURE_INVALID (DCCValidationReport)
	case ACCEPTANCE_RULE_JSON_EXTRACTION_FAILED (DCCValidationReport)
	case ACCEPTANCE_RULE_SERVER_ERROR (DCCValidationReport)
	case INVALIDATION_RULE_CLIENT_ERROR (DCCValidationReport)
	case INVALIDATION_RULE_JSON_ARCHIVE_FILE_MISSING (DCCValidationReport)
	case INVALIDATION_RULE_JSON_ARCHIVE_SIGNATURE_INVALID (DCCValidationReport)
	case INVALIDATION_RULE_JSON_EXTRACTION_FAILED (DCCValidationReport)
	case INVALIDATION_RULE_SERVER_ERROR (DCCValidationReport)
	case NO_NETWORK
	case VALUE_SET_SERVER_ERROR

}
