////
// 🦠 Corona-Warn-App
//

import Foundation

enum DCCValidationError: Error {
	
	// MARK: - Internal
	
	case TECHNICAL_VALIDATION_FAILED (DCCValidationProgress)
	case ACCEPTANCE_RULE_CLIENT_ERROR (DCCValidationProgress)
	case ACCEPTANCE_RULE_JSON_ARCHIVE_FILE_MISSING (DCCValidationProgress)
	case ACCEPTANCE_RULE_JSON_ARCHIVE_SIGNATURE_INVALID (DCCValidationProgress)
	case ACCEPTANCE_RULE_JSON_EXTRACTION_FAILED (DCCValidationProgress)
	case ACCEPTANCE_RULE_SERVER_ERROR (DCCValidationProgress)
	case INVALIDATION_RULE_CLIENT_ERROR (DCCValidationProgress)
	case INVALIDATION_RULE_JSON_ARCHIVE_FILE_MISSING (DCCValidationProgress)
	case INVALIDATION_RULE_JSON_ARCHIVE_SIGNATURE_INVALID (DCCValidationProgress)
	case INVALIDATION_RULE_JSON_EXTRACTION_FAILED (DCCValidationProgress)
	case INVALIDATION_RULE_SERVER_ERROR (DCCValidationProgress)
	case ONBOARDED_COUNTRIES_CLIENT_ERROR (DCCValidationProgress)
	case ONBOARDED_COUNTRIES_JSON_ARCHIVE_FILE_MISSING (DCCValidationProgress)
	case ONBOARDED_COUNTRIES_JSON_ARCHIVE_SIGNATURE_INVALID (DCCValidationProgress)
	case ONBOARDED_COUNTRIES_JSON_EXTRACTION_FAILED (DCCValidationProgress)
	case ONBOARDED_COUNTRIES_SERVER_ERROR (DCCValidationProgress)
	case NO_NETWORK
	case VALUE_SET_SERVER_ERROR

}
