////
// 🦠 Corona-Warn-App
//

struct Checkin {
	let id: Int
	let eventId: String // The ID of the event. Note that the ID is generated by the CWA server. It is stored as base64-encoded string of the guid attribute of Protocol Buffer message Event.
	let eventType: EventType
	let eventDescription: String
	let eventAddress: String
	let eventStart: Date
	let eventEnd: Date
	let eventDefaultCheckInLengthInMinutes: Int
	let eventSignature: String // The signature of the event (provided by the CWA server). It is stored as a base64-encoded string of the signature attribute of Protocol Buffer message SignedEvent.
	let checkinStart: Date
	var checkinEnd: Date

	mutating func update(checkinEnd: Date) {
		self.checkinEnd = checkinEnd
	}
}
